# Generated by Django 4.0.5 on 2022-10-19 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0002_rename_inventory_product_inve'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='inve',
            new_name='inventory',
        ),
    ]
