# Generated by Django 4.0.5 on 2022-10-19 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0003_rename_inve_product_inventory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitems',
            name='cart',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
