# Generated by Django 3.2.8 on 2022-02-15 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0008_saveditem'),
    ]

    operations = [
        migrations.AddField(
            model_name='saveditem',
            name='added',
            field=models.BooleanField(default=False),
        ),
    ]
