# Generated by Django 3.2.8 on 2022-02-16 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0010_remove_saveditem_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='saveditem',
            name='added',
            field=models.IntegerField(default=0),
        ),
    ]
