# Generated by Django 3.2.8 on 2022-02-17 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0011_saveditem_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
