# Generated by Django 4.0.5 on 2022-06-27 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0012_category_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default=True, null=True, upload_to='img'),
        ),
    ]
