# Generated by Django 3.2.8 on 2022-02-16 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfile', '0002_address_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='customer',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='UserProfile.customer'),
        ),
    ]
