# Generated by Django 3.2.8 on 2022-02-18 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfile', '0006_alter_customer_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='username',
        ),
    ]
